server:
  port : 80
spring:
  config:
    import: optional:configtree:/run/secrets/
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hms}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hms
    password: ${mysql_user_password} 
  sql:
    init:
      encoding: UTF-8
      mode: always
      schema-locations: classpath:schema/schema.sql
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  h2:
    console:
      enabled: false
 