server:
  port : 80
spring:
  config:
    import: aws-parameterstore:/config/hms/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#  sql:
#    init:
#      encoding: UTF-8
#      mode: always
#      schema-locations: classpath:schema/schema.sql
  flyway:
    locations: classpath:db/migration/ddl
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  h2:
    console:
      enabled: false
 