spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      encoding: UTF-8
      mode: always
      schema-locations: classpath:schema/schema.sql
#      data-locations: classpath:schema/data-h2.sql
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
  h2:
    console:
      enabled: false
