spring:
  application:
    name: hms
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  messages:
    basename: ValidationMessages
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    aws:
      parameterstore:
        enabled: false
  ai:
    mcp:
      server:
        base-url: /hms
    ollama:
      base-url: ${SPRING_AI_MODEL_HOST:http://192.168.10.11:11434}
      embedding:
        options:
          model: nomic-embed-text
server:
  servlet:
    context-path: /hms
    session:
      timeout: 8h
