spring:
  application:
    name: hms
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  messages:
    basename: ValidationMessages
  flyway:
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  cloud:
    aws:
      parameterstore:
        enabled: false
  ai:
    mcp:
      server:
        base-url: /hms
    ollama:
      base-url: ${SPRING_AI_MODEL_HOST:http://192.168.10.11:11434}
      embedding:
        options:
          model: nomic-embed-text
server:
  servlet:
    session:
      timeout: 8h

# logging:
#   level:
#     # Spring Security の内部処理・認証・フィルターログ
#     org.springframework.security: DEBUG
#     # HTTPリクエストの受け渡しの詳細ログ
#     org.springframework.web: DEBUG
#     # WebAuthn（パスキー）関連処理に絞ったログ
#     org.springframework.security.web.webauthn: TRACE
#     # Hibernate SQLのプレースホルダー(?)に入るパラメータ値を出力
#     org.hibernate.orm.jdbc.bind: TRACE
#     # 独自サービス（WebAuthnServiceのlog.info出力用）
#     com.tarosuke777.hms: DEBUG

app:
  base-domain: home.arpa

  services:
    chat-url: http://www.${app.base-domain}/hc/
    blog-url: http://www.${app.base-domain}/hb/
    videos-url: http://www.${app.base-domain}/hv/videos/
    books-url: http://www.${app.base-domain}/hv/books/
    jenkins-url: http://www.${app.base-domain}/jenkins/
    grafana-url: http://www.${app.base-domain}/grafana/
