Description: Create HMS CodePipeline

Resources:
  # ------------------------------------------------------------#
  #  CodeStarConnections::Connection
  # ------------------------------------------------------------#
  Connection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: SpringBootHmsConnection
      ProviderType: GitHub

  # ------------------------------------------------------------#
  #  S3::Bucket
  # ------------------------------------------------------------#
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hms-artifacts

  # ------------------------------------------------------------#
  #  ECR::PublicRepository
  # ------------------------------------------------------------#
  EcrPublicRepository:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: tarosuke777/spring-boot-hms

  # ------------------------------------------------------------#
  #  IAM::Role
  # ------------------------------------------------------------#
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HmsPipelineRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codepipeline.amazonaws.com
      Policies:
        - PolicyName: HmsPipelinePolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: "*"
              - Effect: Allow
                Action:
                  - iam:PassRole
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecs:DescribeServices
                  - ecs:DescribeTaskDefinition
                  - ecs:RegisterTaskDefinition
                  - ecs:UpdateService
                Resource: "*"

  BuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HmsBuildRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: codebuild.amazonaws.com
      Policies:
        - PolicyName: HmsBuildPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr-public:GetAuthorizationToken
                  - sts:GetServiceBearerToken
                Resource: "*"
              - Effect: Allow
                Action:
                  - ecr-public:GetAuthorizationToken
                  - sts:GetServiceBearerToken
                  - ecr-public:InitiateLayerUpload
                  - ecr-public:UploadLayerPart
                  - ecr-public:CompleteLayerUpload
                  - ecr-public:BatchCheckLayerAvailability
                  - ecr-public:PutImage
                Resource: "*"

  # ------------------------------------------------------------#
  #  CodeBuild::Project
  # ------------------------------------------------------------#
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:5.0
        Type: LINUX_CONTAINER
      Name: HmsCodeBuild
      ServiceRole: !GetAtt BuildRole.Arn

  # ------------------------------------------------------------#
  #  CodePipeline::Pipeline
  # ------------------------------------------------------------#
  CodePipelineProject:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: HmsCodePipeline
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              Configuration:
                ConnectionArn: !Ref Connection
                FullRepositoryId: tarosuke777/spring-boot-hms
                BranchName: main
                OutputArtifactFormat: CODE_ZIP
              RunOrder: 1
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Build
          Actions:
            - Name: BuildAction
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: DeployAction
              InputArtifacts:
                - Name: BuildArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: ECS
                Version: 1
              Configuration:
                ClusterName: HmsCluster
                ServiceName: HmsWebApService
                FileName: imagedefinitions.json
              RunOrder: 1
