name: Test GitHub Actions
on:
  workflow_dispatch:
      inputs:
        branch:
          description: '対象ブランチ'
          required: true
          default: 'main'
jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check branch and file
        run: |
          echo "Branch: ${{ github.ref }}"
