name: PR Agent

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    name: Run PR Agent
    steps:
      - name: PR Agent Action
        uses: Codium-ai/pr-agent@main
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # OPENAI_KEY: ${{ secrets.GEMINI_API_KEY }}
          CONFIG.MODEL: "gemini/gemini-3.5-flash-lite"
          CONFIG.MODEL_TURBO: "gemini/gemini-2.0-flash"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_CONFIG.LANGUAGE: "Japanese"
