name: Java CI with Gradle

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 25
      uses: actions/setup-java@v4
      with:
        java-version: '25' # プロジェクトのJavaバージョン（11, 17, 21など）に合わせて変更してください
        distribution: 'temurin' # 開発でよく使われるEclipse Temurinディストリビューション
        cache: 'gradle' # 依存関係をキャッシュして2回目以降を高速化

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Install Playwright Deps
      run: npx playwright install-deps

    - name: Run Unit Tests with Gradle
      run: ./gradlew test