-- taskテーブルのカラム型を変更
ALTER TABLE task ALTER COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE task ALTER COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

-- taskテーブルに監査用カラムとバージョンカラムを追加
ALTER TABLE task ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE task ADD COLUMN updated_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE task ADD COLUMN version INT NOT NULL DEFAULT 0;
