-- 一旦削除
ALTER TABLE task DROP COLUMN created_at;
ALTER TABLE task DROP COLUMN updated_at;

-- 改めて追加（この構文なら両方のDBでほぼ共通です）
ALTER TABLE task ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE task ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);

-- taskテーブルに監査用カラムとバージョンカラムを追加
ALTER TABLE task ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE task ADD COLUMN updated_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE task ADD COLUMN version INT NOT NULL DEFAULT 0;
