-- bookテーブルに運用・監査用のカラムを追加
ALTER TABLE book ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE book ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE book ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE book ADD COLUMN updated_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE book ADD COLUMN version INT NOT NULL DEFAULT 0;
