-- diaryテーブルに運用・監査用のカラムを追加
ALTER TABLE diary ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE diary ADD COLUMN updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
ALTER TABLE diary ADD COLUMN created_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE diary ADD COLUMN updated_by VARCHAR(255) NOT NULL DEFAULT 'SYSTEM';
ALTER TABLE diary ADD COLUMN version INT NOT NULL DEFAULT 0;
